/*!
 * @file GaloisField.h
 * @brief Header file for class GaloisField
 * @details Definition of the class GaloisField
 */

#include "Polynom.h"

/*!
 * @autor Pashchenko Dmytro
 * @brief class GaloisField that describes finite field of polynomials 
 * generated by irreducible polynomial
 * @details
 * defines a field of polynomials over the field GF(p) (p is prime)
 * irreducible polynomial of power "degree"
 */
class GaloisField {
private:
	// irreducible polynomial that defines the field
	Polynom irreducible;
	// prime number that defines field GF(p) of coeffcients
	long long prime;
	// power of irreducible polynomial
	long long degree;

public:
	GaloisField() :prime(2), degree(2) {
		irreducible = Polynom::findIrreduciblePolynomial(2, 2);
	}
	
	GaloisField(long long prime, long long degree) :prime(prime), degree(degree){
		irreducible = Polynom::findIrreduciblePolynomial(prime, degree);
	}
	long long getPrime() const { return prime; }
	long long getDegree() const { return degree; }
	Polynom getIrreducible() const {
		return irreducible;
	}

	std::vector<Polynom> getNIrreducible(int n) const {
		return Polynom::nIrreduciblePolynomials(prime, degree, n);
	}

	void setIrreducible(int n, int index) {
		std::vector<Polynom> temp = getNIrreducible(n);
		irreducible = temp[index % n];
	}

	void setIrreducible(Polynom p) {
		irreducible = p;
		degree = p.getPolyPower();
	}

	/*!
     * @brief Adds polynomials in the field
     */
	Polynom add(Polynom const& left, Polynom const& right) const {
		if (left.getPrime() != right.getPrime() || 
			left.getPrime() != irreducible.getPrime()) return Polynom();
		return (left + right) % irreducible;
	}

	/*!
     * @brief Subtracts polynomials in the field
     */
	Polynom subtract(Polynom const& left, Polynom const& right) const {
		if (left.getPrime() != right.getPrime() || 
			left.getPrime() != irreducible.getPrime()) return Polynom();
		return (left - right) % irreducible;
	}

	/*!
     * @brief Multiplies polynomials in the field
     */
	Polynom multiply(Polynom const& left, Polynom const& right) const {
		if (left.getPrime() != right.getPrime() || 
			left.getPrime() != irreducible.getPrime()) return Polynom();
		return (left * right) % irreducible;
	}

	/*!
     * @brief Implements extended Euclidean algorithm
     */
    Polynom extendedEuclideanAlgorithm(Polynom a, Polynom b, Polynom *x, Polynom *y)const {
        long long prime=a.getPrime();

        if (a == Polynom(prime,std::vector<long long>{0}))
        {
            *x = Polynom(prime,std::vector<long long>{0});
            *y = Polynom(prime,std::vector<long long>{1});
            return b;
        }
        Polynom x1, y1;
        Polynom d = extendedEuclideanAlgorithm(b%a, a, &x1, &y1);
        *x = y1 - (b / a) * x1;
        *y = x1;
        return d;
    }

	/*!
     * @brief Finds the inverse of a given polynomial in the field
     */
    Polynom getInverse(Polynom const& polynom) const {
        Polynom x;
        Polynom y;
        extendedEuclideanAlgorithm(polynom, irreducible, &x, &y);
        x = (x % irreducible + irreducible) % irreducible;
        return x;
    }

	/*!
     * @brief Divides polynomials in the field
     */
	Polynom divide(Polynom const& left, Polynom const& right) const {
		if (left.getPrime() != right.getPrime() || 
			left.getPrime() != irreducible.getPrime()) return Polynom();
		return (left * getInverse(right)) % irreducible;
	}

	/*!
     * @brief Takes the remainder of a division of polynomials in the field
     */
	Polynom mod(Polynom const& left, Polynom const& right) const {
		if (left.getPrime() != right.getPrime() ||
			left.getPrime() != irreducible.getPrime()) return Polynom();
		return (left % right) % irreducible;
	}

	/*!
     * @brief Finds the derivative of a given polynomial
     */
	Polynom derivative(Polynom const& polynom) const {
		return polynom.derivative() % irreducible;
	}
};